import productsRouter from"./routes/products.js";
import express from "express";
import cors from "cors";
import dotenv from "dotenv";
dotenv.config();
const app=express();
const PORT=process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.get("/api/health",(req,res)=>{res.json({success:true,message:"To API is running"});});
app.use("/api/products",productsRouter);
app.listen(PORT,()=>{console.log(`TO API running on port${PORT}`);});
